

create table if not exists DIRECTORY_TYPE(

    DIRECTORY_TYPE_ID BIGINT NOT NULL,
    DIRECTORY_TYPE CHARACTER VARYING(20) NOT NULL,
    DESCRIPTION CHARACTER VARYING(20) NOT NULL

);

alter table DIRECTORY_TYPE add constraint primary key (DIRECTORY_TYPE_ID);


create table if not exists DIRECTORY(
    DIRECTORY_ID BIGINT NOT NULL ,
    DIRECTORY_TYPE BIGINT NOT NULL ,
    NAME CHARACTER VARYING(20) NOT NULL ,
    CODE CHARACTER VARYING(20) NOT NULL ,
    DIRECTORY_ATTRS JSON NULL
);

ALTER TABLE DIRECTORY ADD CONSTRAINT PRIMARY KEY (DIRECTORY_ID);

ALTER TABLE DIRECTORY ADD CONSTRAINT FOREIGN KEY (DIRECTORY_TYPE) REFERENCES DIRECTORY_TYPE(DIRECTORY_TYPE);