server:
  port: 8091

spring:
  application:
    name: cinema_fapi
  mail:
    host: smtp.yandex.ru
    port: 465
    username:
    password:
    protocol: smtps
    debug: true
    properties:
      "mail.smtp.ssl.enable": true
      "mail.transport.protocol": smpt
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true

jwt:
  secret: qwerty
  expired: 1000000